# CA-Net + full_split (9 ch with pr split)
model_name:   canet_full_split
model_class:  iso_unet.baseline_canet.CANetBaseline
dataset_kind: single_frame
input_set:    full_split
seq_len:      12
batch_size:   8
lr:           1.0e-3
max_epochs:   1000
patience:     10
max_batch:    3000
gradient_clip_val: 1.0

model_kwargs:
  feature_scale:  4
  H:              90
  W:              180
  is_deconv:      true
  dsv_channels:   4
